export const POST_LIST = [
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title',
    comments: 0,
    likes: 0,
    location: 'Location',
  },
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title 2',
    comments: 32,
    likes: 123,
    location: 'Lviv',
  },
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title 3',
    comments: 234,
    likes: 2345,
    location: 'Kyiv',
  },
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title 4',
    comments: 12,
    likes: 32,
    location: 'Kharkiv',
  },
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title 5',
    comments: 123,
    likes: 123123,
    location: 'Odesa',
  },
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title 6',
    comments: 90,
    likes: 798,
    location: 'Poltava',
  },
  {
    imageURI: 'https://source.unsplash.com/random/350x240',
    title: 'Title 7',
    comments: 49,
    likes: 2348,
    location: 'Vinnytsia',
  },
];
